/**
 * Generates global.css and the Tailwind colour map from theme/tokens.ts.
 *
 *   node theme/generate-css.mjs
 *
 * Tokens are defined once, in TypeScript, where they're type-checked and
 * contrast-verified. Hand-maintaining a parallel copy in CSS is how the two
 * drift, which is the whole problem this work exists to fix — so the CSS is
 * generated and the file says not to edit it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const src = readFileSync(join(here, "tokens.ts"), "utf8");

function parseTheme(name) {
  const start = src.indexOf(`export const ${name}: ThemeTokens = {`);
  const body = src.slice(start, src.indexOf("\n};", start));
  const out = {};
  for (const m of body.matchAll(/^\s{2}(\w+):\s*"([^"]+)"/gm)) out[m[1]] = m[2];
  return out;
}

/** camelCase -> kebab-case, so `surfaceRaised` becomes `--c-surface-raised`. */
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const light = parseTheme("lightTokens");
const dark = parseTheme("darkTokens");

const declare = (tokens) =>
  Object.entries(tokens)
    .map(([k, v]) => `  --c-${kebab(k)}: ${v};`)
    .join("\n");

// Outside @layer base on purpose: a `.dark` rule inside the base layer is
// dropped by Tailwind's build. Verified, not assumed.
const css = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* GENERATED by theme/generate-css.mjs from theme/tokens.ts — do not edit.
   Change the tokens, run the generator, and the contrast verifier. */

:root {
${declare(light)}
}

.dark {
${declare(dark)}
}
`;

writeFileSync(join(root, "global.css"), css);

const names = Object.keys(light).map(kebab);
writeFileSync(
  join(here, "colors.generated.js"),
  `// GENERATED by theme/generate-css.mjs — do not edit.\n` +
    `// Semantic colour names for Tailwind, each resolving to a CSS variable\n` +
    `// that flips with the .dark class.\n` +
    `module.exports = {\n` +
    names.map((n) => `  "${n}": "var(--c-${n})",`).join("\n") +
    `\n};\n`
);

console.log(`global.css + theme/colors.generated.js written (${names.length} tokens x 2 themes)`);
